load(
    "//bazel:vpg_build_system.bzl",
    "vpg_catch_test",
)

vpg_catch_test(
    name = "contiguous_page_range_test",
    srcs = [
        "contiguous_page_range_test.cc",
    ],
    deps = [
        "//:vpg_lib",
    ],
)

vpg_catch_test(
    name = "page_mapped_value_range_test",
    srcs = [
        "page_mapped_value_range_test.cc",
    ],
    deps = [
        "//:vpg_lib",
    ],
)

vpg_catch_test(
    name = "vector_test",
    srcs = [
        "vector_test.cc",
    ],
    deps = [
        "//:vpg_lib",
    ],
)
